### ISSUE TITLE
pom Plays and Pauses My Spotify Music

### ISSUE THREAD

**Issue by qw3rtman** [edelprino/pom#7]
`pom start` plays it and `pom stop` pauses it. Don't know if this is intentional or not, but thought I would create an issue just in case.

```
Spotify version 1.0.14.124.g4dfabc51
Node v0.12.0
OS X 10.10.4
```

**Comment by edelprino** [comment]
Hi, yes, is intentional. You can see in `~/.pom.yml` every instructions run at pomodoro start and pomodoro end. One of this is start or play spotify.

https://github.com/edelprino/pom/blob/master/.pom.yml
