### ISSUE TITLE
Are breaks working?

### ISSUE THREAD

**Issue by deini** [edelprino/pom#8]
I can't seem to get breaks to work 

`pom -b start`
`pom break`
`pom break start`
`pom --break start`

Nothing seems to trigger them. What am I missing?

**Comment by edelprino** [comment]
Uhm... I think that `break` command is brokend... I fix it as soon as possible!! Sorry!! :)

**Comment by edelprino** [comment]
In version 1 of pom I've change a lot of things, like time environment for short and long break... That changes fix also this bug.
